x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"

services:
  # Uncomment if not using generate script
  # records-ui:
  #   image: records-ui:latest
  #   container_name: records-ui
  #   build:
  #     context: ./records-ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4173:4173
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 250M
  #   restart: unless-stopped
  #   environment:
  #     - FRONTEND_ADDR
  #     - NODE_ENV=production
  #   logging: *logging

  records-service:
    image: records-service:latest
    container_name: records-service
    build:
      context: ./records-service
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.version=1,deployment.environment=dev
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS}
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_INFERRED_SPANS_ENABLED=true
      - OTEL_INFERRED_SPANS_LOGGING_ENABLED=true
      #- OTEL_JAVAAGENT_DEBUG=true
    ports:
      - 8080:8080

  otel-collector:
    build:
      context: ./otel-collector
    ports:
      - "4318:4318"
    env_file:
      - .env
    environment:
      - ELASTIC_ENDPOINT=${ELASTIC_ENDPOINT}
      - ELASTIC_API_KEY=${ELASTIC_API_KEY}
    command: ["--config=/etc/otelcol/config.yaml", "--set=service.telemetry.logs.level=debug"]

  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    ports:
      - "8123:8123"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - otel-collector